let num1 = prompt('Digite um número')
let num2 = prompt(' Digite outro número')

let soma = parseInt(num1) + parseInt(num2)
let sub = parseInt(num1) - parseInt (num2)
let mult = parseInt(num1) * parseInt(num2)
let div = parseInt(num1) / parseInt(num2)
console.log('A soma é: ' + soma)
console.log('A subtração é: ' + sub)
console.log('A multiplicação é '+ mult)
console.log('A divisão é: ' + div)
